### ISSUE TITLE
Comments on new-tree/doc/NewTreeStructure.adoc

### ISSUE THREAD

**Issue by nielsklazenga** [bio-org-au/services-g3-retired#1]
Great document. Can't be faulted as a specification. Two suggestions:

1. The versioning strategy seems to be very much inspired by the APC process, where you can actually speak of periodical bodies of work that can be published. Any other use case for the NSL trees I can think of is much more dynamic with frequent occurrence of one or a few changes that need to become live immediately in order for them to be available to external applications that make use of the tree. The proposed approach of having a published tree and a work tree could work for VicFlora, for example, but we would publish every change (or day's worth of changes). And then we might have forgotten something or someone spots an error, so that is another version. This can very quickly lead to a high number of versions and large amount of data to be stored, which is identified as the greatest risk of the new strategy. If then a decision has to be made to rate-limit the versions, the NSL trees become unfit for purpose.
&nbsp;&nbsp;&nbsp;&nbsp;It makes more sense to me to have a HEAD revision of a tree, which can be worked on directly by people who have the permission, and periodically save a snapshot of the tree as a version. This gives much better control over how much storage is required, while still having the increased simplicity the proposed approach tries to achieve. It also saves the hassle of having to create a work tree and then publish it, every time you make a change.

2. My suggested approach doesn't preclude having draft trees that can be published back to the main tree, but I think the use case in the document (the Orchidaceae) and any other use case I can think of, might be better served with the ability to check out a subtree from a tree, work on it and check it back in. This subtree can be established as a temporary tree and can have a set of user permissions to control who can edit it that is different from that of the main tree. I think this completely negates the risk of merge conflicts and it also enables collaboration (I imagine a draft tree is only accessible to a single user). Moreover, the ability to merge subtrees into trees is already a requirement, so you'll kill two birds with one stone.

**Comment by pmcneil** [comment]
Thanks for the feedback Niels.

The versioning does not prevent any of what you are suggesting. Daily versions are entirely feasible and the storage implications are not that onerous.

A couple of things to note.
1. the draft tree(s) can be publicly accessible, or accessible to a group.
2. you can have as many draft trees/clones as you like at one time and merge other changes to them
3. draft trees take seconds to create (even very large ones) and you can discard them
4. you can create trees from copies of other trees and make composite trees, so you *can* just work on a branch - which can be part of another composite tree. The granularity of trees is something that will be decided by use.
5. publishing gives you editorial control over changes.

Using a head revision with a snapshot **is** publishing a version because we need to maintain permalinks from tree elements to the version of the tree at the time it was referenced. For larger trees like APC, limiting to daily published revisions makes sense, both in terms of change sets and storage. In smaller trees we don't really have a storage issue, but daily published **sets of changes** still make a lot of sense.

If you need to make a single change and publish it straight away, go ahead. With this structure we have the ability to archive off old versions, we could even delete interim versions and still maintain links. That would simply be a policy decision i.e. you can publish multiple changes in a day, and just keep the latest version at the end of the day. This would be data loss free in 99.99+% of practical cases. (Links from interim versions are simply forwarded to the last version published, a create/delete in a day simply wouldn't show up.)

From a data management point of view using the git clone/merge approach is more efficient and does what you  want, it allows multiple draft versions (clones) which can be merged/copied/deleted etc. It allows long running change sets to run alongside minor changes (change branches). Yes we need published changes to be merged into the ongoing draft branches to keep them synchronised, but this isn't a bad thing, it shows you potential conflicts up front and is largely automatic.

Merging back just a branch is feasible. It requires extra steps and validation to maintain a consistent tree, but that is required for composite trees anyway. Having a full copy of tree (which is really a branch of a tree of life anyway) allows us to simply and quickly check consistency, like if the name appears elsewhere in the tree, while you make changes.

**Comment by nielsklazenga** [comment]
Excellent!

**Comment by ghwhitbread** [comment]
Comment on Niels's comments:

The original tree spec. Is very much as Niels describes - a continuously changing tree on persistent (citable) public view with checkout/checkback private views to allow for more complex 1+ group editing away from the published tree.   

The framework to achieve this is actually in production (mostly) but there are performance issues. And now that the lead developer is leaving, there are also issues around the design's complexity.   

The workspace idea was introduced, in the existing framework, to improve tree performance and to provide editorial integrity around taxon circumscription within a branch. e.g. adding 3 species to a new Genus should be an atomic operation so we don't have a different citatable genus with first one, then two, then three species.  

The workspace was initially intended to improve user experience around tree management tasks in the instance editor by holding back expensive  tree writes and placing their publication under user, or session, control.  But once they existed - made persistent and coupled with the more granular authorization regime, workspaces also become the ideal container for longer term, group editing of branches away from the cite-every-version  requirement.

A one workspace per tree constraint , and the restriction on workflow possibilities that imposed, was added to simplify initial implementation.   

The "new Tree" document deals with an alternative implementation and it starts from the premise of this simplified model.   If the proposed workflow is too restrictive, we will need this document to address how this new implementation can better meet the original requirements and for the test suite to demonstrate this .  Saying that it will is probably not enough.

**Comment by nielsklazenga** [comment]
Thanks Greg. I just wanted to make sure that the use case of frequent small edits was considered and was perfectly happy with Peter's explanation. The complexity of the current trees is indeed an issue, also for the users (well, users like me).

I will be happy to help with the testing.
